import { describe, expect, it } from 'vitest'

import {
  KANBAN_CLIENT_EVENTS,
  KANBAN_CLIENT_OPERATIONS,
  KANBAN_OPERATION_COMMANDS,
  KanbanClient,
  parseKanbanLiveEvent,
  type KanbanOperationName,
  type KanbanTransport,
} from './client.js'
import type { EventEnvelope } from './types.js'

describe('generated client', () => {
  it('maps every operation to its typed Tauri command', () => {
    expect(KANBAN_OPERATION_COMMANDS).toStrictEqual({
      'health.get': 'health_get',
      'diagnostics.export': 'diagnostics_export',
      'initiative.create': 'initiative_create',
      'initiative.rename': 'initiative_rename',
      'initiative.archive': 'initiative_archive',
      'initiative.list': 'initiative_list',
      'project.register': 'project_register',
      'project.archive': 'project_archive',
      'project.list': 'project_list',
      'plan.create': 'plan_create',
      'plan.spec.add': 'plan_spec_add',
      'plan.spec.remove': 'plan_spec_remove',
      'plan.spec.move': 'plan_spec_move',
      'plan.edge.add': 'plan_edge_add',
      'plan.edge.remove': 'plan_edge_remove',
      'plan.activate': 'plan_activate',
      'plan.replan': 'plan_replan',
      'plan.complete': 'plan_complete',
      'plan.cancel': 'plan_cancel',
      'plan.archive': 'plan_archive',
      'plan.list': 'plan_list',
      'plan.get': 'plan_get',
      'plan.diagnostics': 'plan_diagnostics',
      'spec.create': 'spec_create',
      'spec.content.update': 'spec_content_update',
      'spec.version.approve': 'spec_version_approve',
      'spec.version.supersede': 'spec_version_supersede',
      'spec.plan.join': 'spec_plan_join',
      'spec.execution.move': 'spec_execution_move',
      'spec.list': 'spec_list',
      'spec.get': 'spec_get',
      'spec.version.get': 'spec_version_get',
      'spec.coverage.check': 'spec_coverage_check',
      'spec.coverage.matrix': 'spec_coverage_matrix',
      'ticket.create': 'ticket_create',
      'ticket.bug.qualify': 'ticket_bug_qualify',
      'ticket.bug.facts': 'ticket_bug_facts',
      'ticket.list': 'ticket_list',
      'ticket.get': 'ticket_get',
      'ticket.dependency.add': 'ticket_dependency_add',
      'ticket.dependency.remove': 'ticket_dependency_remove',
      'ticket.blocker.add': 'ticket_blocker_add',
      'ticket.blocker.remove': 'ticket_blocker_remove',
      'ticket.dependencies': 'ticket_dependencies',
      'ticket.readiness': 'ticket_readiness',
      'ticket.assign': 'ticket_assign',
      'ticket.transition': 'ticket_transition',
      'ticket.park': 'ticket_park',
      'ticket.unpark': 'ticket_unpark',
      'ticket.schedule': 'ticket_schedule',
      'ticket.cancel': 'ticket_cancel',
      'ticket.review': 'ticket_review',
      'ticket.prioritise': 'ticket_prioritise',
      'ticket.edit': 'ticket_edit',
      'ticket.emergency.override': 'ticket_emergency_override',
      'ticket.spec.move': 'ticket_spec_move',
      'ticket.graph.propose': 'ticket_graph_propose',
      'ticket.graph.approve': 'ticket_graph_approve',
      'ticket.graph.list': 'ticket_graph_list',
      'ticket.reassign': 'ticket_reassign',
      'profile.define': 'profile_define',
      'profile.update': 'profile_update',
      'profile.retire': 'profile_retire',
      'profile.list': 'profile_list',
      'profile.get': 'profile_get',
      'capacity.defaults.get': 'capacity_defaults_get',
      'capacity.defaults.update': 'capacity_defaults_update',
      'capacity.settings.get': 'capacity_settings_get',
      'capacity.settings.update': 'capacity_settings_update',
      'dispatch.request': 'dispatch_request',
      'dispatch.claim': 'dispatch_claim',
      'dispatch.queue': 'dispatch_queue',
      'timeline.query': 'timeline_query',
      'comment.create': 'comment_create',
      'comment.edit': 'comment_edit',
      'comment.revisions': 'comment_revisions',
      'ruling.record': 'ruling_record',
      'ruling.supersede': 'ruling_supersede',
      'ruling.list': 'ruling_list',
      'deferral.record': 'deferral_record',
      'deferral.supersede': 'deferral_supersede',
      'deferral.list': 'deferral_list',
      'evidence.attach': 'evidence_attach',
      'evidence.list': 'evidence_list',
      'herdr.settings.get': 'herdr_settings_get',
      'herdr.settings.update': 'herdr_settings_update',
      'herdr.defaults.get': 'herdr_defaults_get',
      'herdr.defaults.update': 'herdr_defaults_update',
      'workspace.register': 'workspace_register',
      'workspace.observe': 'workspace_observe',
      'workspace.retire': 'workspace_retire',
      'workspace.list': 'workspace_list',
      'lane.create': 'lane_create',
      'lane.workspace.assign': 'lane_workspace_assign',
      'lane.workspace.release': 'lane_workspace_release',
      'lane.ticket.assign': 'lane_ticket_assign',
      'lane.ticket.release': 'lane_ticket_release',
      'lane.list': 'lane_list',
      'clone.create': 'clone_create',
      'clone.remove': 'clone_remove',
      'export.render': 'export_render',
      'export.drift': 'export_drift',
    })
  })

  it('lists only application-layer operations', () => {
    expect(KANBAN_CLIENT_OPERATIONS).toStrictEqual([
      'health.get',
      'diagnostics.export',
      'initiative.create',
      'initiative.rename',
      'initiative.archive',
      'initiative.list',
      'project.register',
      'project.archive',
      'project.list',
      'plan.create',
      'plan.spec.add',
      'plan.spec.remove',
      'plan.spec.move',
      'plan.edge.add',
      'plan.edge.remove',
      'plan.activate',
      'plan.replan',
      'plan.complete',
      'plan.cancel',
      'plan.archive',
      'plan.list',
      'plan.get',
      'plan.diagnostics',
      'spec.create',
      'spec.content.update',
      'spec.version.approve',
      'spec.version.supersede',
      'spec.plan.join',
      'spec.execution.move',
      'spec.list',
      'spec.get',
      'spec.version.get',
      'spec.coverage.check',
      'spec.coverage.matrix',
      'ticket.create',
      'ticket.bug.qualify',
      'ticket.bug.facts',
      'ticket.list',
      'ticket.get',
      'ticket.graph.propose',
      'ticket.graph.approve',
      'ticket.graph.list',
      'ticket.spec.move',
      'ticket.dependency.add',
      'ticket.dependency.remove',
      'ticket.blocker.add',
      'ticket.blocker.remove',
      'ticket.dependencies',
      'ticket.readiness',
      'ticket.assign',
      'ticket.transition',
      'ticket.park',
      'ticket.unpark',
      'ticket.schedule',
      'ticket.cancel',
      'ticket.review',
      'ticket.prioritise',
      'ticket.edit',
      'ticket.emergency.override',
      'ticket.reassign',
      'profile.define',
      'profile.update',
      'profile.retire',
      'profile.list',
      'profile.get',
      'capacity.defaults.get',
      'capacity.defaults.update',
      'capacity.settings.get',
      'capacity.settings.update',
      'dispatch.request',
      'dispatch.claim',
      'dispatch.queue',
      'timeline.query',
      'comment.create',
      'comment.edit',
      'comment.revisions',
      'ruling.record',
      'ruling.supersede',
      'ruling.list',
      'deferral.record',
      'deferral.supersede',
      'deferral.list',
      'evidence.attach',
      'evidence.list',
      'herdr.settings.get',
      'herdr.settings.update',
      'herdr.defaults.get',
      'herdr.defaults.update',
      'workspace.register',
      'workspace.observe',
      'workspace.retire',
      'workspace.list',
      'lane.create',
      'lane.workspace.assign',
      'lane.workspace.release',
      'lane.ticket.assign',
      'lane.ticket.release',
      'lane.list',
      'clone.create',
      'clone.remove',
      'export.render',
      'export.drift',
    ])
  })

  it('lists only application-layer live events', () => {
    expect(KANBAN_CLIENT_EVENTS).toStrictEqual([
      'initiative.created',
      'initiative.renamed',
      'initiative.archived',
      'project.registered',
      'project.archived',
      'plan.created',
      'plan.activated',
      'plan.replanned',
      'plan.completed',
      'plan.cancelled',
      'plan.archived',
      'spec.created',
      'spec.planned',
      'spec.version.approved',
      'spec.version.superseded',
      'spec.execution.moved',
      'ticket.created',
      'ticket.assigned',
      'ticket.state.changed',
      'ticket.edited',
      'profile.defined',
      'profile.updated',
      'profile.retired',
      'comment.created',
      'comment.edited',
      'ruling.recorded',
      'ruling.superseded',
      'deferral.recorded',
      'deferral.superseded',
      'evidence.attached',
      'evidence.listed',
      'workspace.registered',
      'workspace.observed',
      'workspace.retired',
      'lane.created',
      'lane.workspace.assigned',
      'lane.workspace.released',
      'lane.ticket.assigned',
      'lane.ticket.released',
      'clone.created',
      'clone.removed',
      'dispatch.requested',
      'dispatch.claimed',
    ])
  })

  it('refuses unknown live event envelopes', () => {
    const envelope: EventEnvelope = {
      sequence: 1,
      event_type: 'counter.bumped',
      payload: { to: 1 },
    }

    expect(() => parseKanbanLiveEvent(envelope)).toThrow(
      'unknown live event type `counter.bumped`',
    )
  })

  it('routes queries through the transport boundary', async () => {
    const calls: Array<{ name: string; request: unknown }> = []
    const transport: KanbanTransport = {
      query: async <Request, Response>(
        name: KanbanOperationName,
        request: Request,
      ): Promise<Response> => {
        calls.push({ name, request })
        return { connected: true, service_version: '0.1.0' } as Response
      },
      command: async () => {
        throw new Error('unexpected command')
      },
      subscribe: () => () => undefined,
    }
    const client = new KanbanClient(transport)

    await client.queryHealthGet()

    expect(calls).toStrictEqual([{ name: 'health.get', request: {} }])
  })
})
