// Generated by kanban-contracts-gen. Do not edit.
import type { CommentCreateRequest, CommentEditRequest, CommentRecord, CommentRevisionsQuery, CommentRevisionsResponse, DeferralIdentity, DeferralListQuery, DeferralListResponse, DeferralRecord, DeferralRecordRequest, DeferralSupersedeRequest, EventEnvelope, EvidenceAttachRequest, EvidenceListRequest, EvidenceListResponse, EvidenceListSummary, EvidenceRecord, HealthQuery, HealthResponse, InitiativeArchiveRequest, InitiativeCreateRequest, InitiativeListQuery, InitiativeListResponse, InitiativeRecord, InitiativeRenameRequest, ProjectArchiveRequest, ProjectListQuery, ProjectListResponse, ProjectRecord, ProjectRegisterRequest, RulingIdentity, RulingListQuery, RulingListResponse, RulingRecord, RulingRecordRequest, RulingSupersedeRequest, TimelineQuery, TimelineQueryResponse } from './types.js';

export const KANBAN_CLIENT_OPERATIONS = [
  'health.get',
  'initiative.create',
  'initiative.rename',
  'initiative.archive',
  'initiative.list',
  'project.register',
  'project.archive',
  'project.list',
  'timeline.query',
  'comment.create',
  'comment.edit',
  'comment.revisions',
  'ruling.record',
  'ruling.supersede',
  'ruling.list',
  'deferral.record',
  'deferral.supersede',
  'deferral.list',
  'evidence.attach',
  'evidence.list',
] as const;

export type KanbanOperationName = (typeof KANBAN_CLIENT_OPERATIONS)[number];

export const KANBAN_CLIENT_EVENTS = [
  'initiative.created',
  'initiative.renamed',
  'initiative.archived',
  'project.registered',
  'project.archived',
  'comment.created',
  'comment.edited',
  'ruling.recorded',
  'ruling.superseded',
  'deferral.recorded',
  'deferral.superseded',
  'evidence.attached',
  'evidence.listed',
] as const;

export type KanbanEventName = (typeof KANBAN_CLIENT_EVENTS)[number];

export type KanbanEventPayloadMap = {
  'initiative.created': InitiativeRecord;
  'initiative.renamed': InitiativeRecord;
  'initiative.archived': InitiativeRecord;
  'project.registered': ProjectRecord;
  'project.archived': ProjectRecord;
  'comment.created': CommentRecord;
  'comment.edited': CommentRecord;
  'ruling.recorded': RulingIdentity;
  'ruling.superseded': RulingIdentity;
  'deferral.recorded': DeferralIdentity;
  'deferral.superseded': DeferralIdentity;
  'evidence.attached': EvidenceRecord;
  'evidence.listed': EvidenceListSummary;
};

export type KanbanLiveEvent = {
  [Name in KanbanEventName]: {
    sequence: number;
    event_type: Name;
    payload: KanbanEventPayloadMap[Name];
  };
}[KanbanEventName];

export function isKanbanEventName(value: string): value is KanbanEventName {
  return (KANBAN_CLIENT_EVENTS as readonly string[]).includes(value);
}

export function parseKanbanLiveEvent(envelope: EventEnvelope): KanbanLiveEvent {
  if (!isKanbanEventName(envelope.event_type)) {
    throw new Error(`unknown live event type \`${envelope.event_type}\``);
  }
  return envelope as KanbanLiveEvent;
}

export interface KanbanTransport {
  query<Request, Response>(name: KanbanOperationName, request: Request): Promise<Response>;
  command<Request, Response>(name: KanbanOperationName, request: Request): Promise<Response>;
  subscribe(handler: (event: KanbanLiveEvent) => void): () => void;
}

export class KanbanClient {
  constructor(private readonly transport: KanbanTransport) {}

  queryHealthGet(request: HealthQuery = {}): Promise<HealthResponse> {
    return this.transport.query('health.get', request);
  }

  commandInitiativeCreate(request: InitiativeCreateRequest): Promise<InitiativeRecord> {
    return this.transport.command('initiative.create', request);
  }

  commandInitiativeRename(request: InitiativeRenameRequest): Promise<InitiativeRecord> {
    return this.transport.command('initiative.rename', request);
  }

  commandInitiativeArchive(request: InitiativeArchiveRequest): Promise<InitiativeRecord> {
    return this.transport.command('initiative.archive', request);
  }

  queryInitiativeList(request: InitiativeListQuery = {}): Promise<InitiativeListResponse> {
    return this.transport.query('initiative.list', request);
  }

  commandProjectRegister(request: ProjectRegisterRequest): Promise<ProjectRecord> {
    return this.transport.command('project.register', request);
  }

  commandProjectArchive(request: ProjectArchiveRequest): Promise<ProjectRecord> {
    return this.transport.command('project.archive', request);
  }

  queryProjectList(request: ProjectListQuery = {}): Promise<ProjectListResponse> {
    return this.transport.query('project.list', request);
  }

  queryTimelineQuery(request: TimelineQuery): Promise<TimelineQueryResponse> {
    return this.transport.query('timeline.query', request);
  }

  commandCommentCreate(request: CommentCreateRequest): Promise<CommentRecord> {
    return this.transport.command('comment.create', request);
  }

  commandCommentEdit(request: CommentEditRequest): Promise<CommentRecord> {
    return this.transport.command('comment.edit', request);
  }

  queryCommentRevisions(request: CommentRevisionsQuery): Promise<CommentRevisionsResponse> {
    return this.transport.query('comment.revisions', request);
  }

  commandRulingRecord(request: RulingRecordRequest): Promise<RulingRecord> {
    return this.transport.command('ruling.record', request);
  }

  commandRulingSupersede(request: RulingSupersedeRequest): Promise<RulingRecord> {
    return this.transport.command('ruling.supersede', request);
  }

  queryRulingList(request: RulingListQuery): Promise<RulingListResponse> {
    return this.transport.query('ruling.list', request);
  }

  commandDeferralRecord(request: DeferralRecordRequest): Promise<DeferralRecord> {
    return this.transport.command('deferral.record', request);
  }

  commandDeferralSupersede(request: DeferralSupersedeRequest): Promise<DeferralRecord> {
    return this.transport.command('deferral.supersede', request);
  }

  queryDeferralList(request: DeferralListQuery): Promise<DeferralListResponse> {
    return this.transport.query('deferral.list', request);
  }

  commandEvidenceAttach(request: EvidenceAttachRequest): Promise<EvidenceRecord> {
    return this.transport.command('evidence.attach', request);
  }

  commandEvidenceList(request: EvidenceListRequest): Promise<EvidenceListResponse> {
    return this.transport.command('evidence.list', request);
  }
}
