// Generated by kanban-contracts-gen. Do not edit.
import type { CommentCreateRequest, CommentEditRequest, CommentRecord, CommentRevisionsQuery, CommentRevisionsResponse, DeferralListQuery, DeferralListResponse, DeferralRecord, DeferralRecordRequest, DeferralSupersedeRequest, EventEnvelope, HealthQuery, HealthResponse, InitiativeArchiveRequest, InitiativeCreateRequest, InitiativeListQuery, InitiativeListResponse, InitiativeRecord, InitiativeRenameRequest, RulingListQuery, RulingListResponse, RulingRecord, RulingRecordRequest, RulingSupersedeRequest, TimelineQuery, TimelineQueryResponse } from './types.js';

export const KANBAN_CLIENT_OPERATIONS = [
  'health.get',
  'initiative.create',
  'initiative.rename',
  'initiative.archive',
  'initiative.list',
  'timeline.query',
  'comment.create',
  'comment.edit',
  'comment.revisions',
  'ruling.record',
  'ruling.supersede',
  'ruling.list',
  'deferral.record',
  'deferral.supersede',
  'deferral.list',
] as const;

export type KanbanOperationName = (typeof KANBAN_CLIENT_OPERATIONS)[number];

export interface KanbanTransport {
  query<Request, Response>(name: KanbanOperationName, request: Request): Promise<Response>;
  command<Request, Response>(name: KanbanOperationName, request: Request): Promise<Response>;
  subscribe(handler: (event: EventEnvelope) => void): () => void;
}

export class KanbanClient {
  constructor(private readonly transport: KanbanTransport) {}

  queryHealthGet(request: HealthQuery = {}): Promise<HealthResponse> {
    return this.transport.query('health.get', request);
  }

  commandInitiativeCreate(request: InitiativeCreateRequest): Promise<InitiativeRecord> {
    return this.transport.command('initiative.create', request);
  }

  commandInitiativeRename(request: InitiativeRenameRequest): Promise<InitiativeRecord> {
    return this.transport.command('initiative.rename', request);
  }

  commandInitiativeArchive(request: InitiativeArchiveRequest): Promise<InitiativeRecord> {
    return this.transport.command('initiative.archive', request);
  }

  queryInitiativeList(request: InitiativeListQuery = {}): Promise<InitiativeListResponse> {
    return this.transport.query('initiative.list', request);
  }

  queryTimelineQuery(request: TimelineQuery): Promise<TimelineQueryResponse> {
    return this.transport.query('timeline.query', request);
  }

  commandCommentCreate(request: CommentCreateRequest): Promise<CommentRecord> {
    return this.transport.command('comment.create', request);
  }

  commandCommentEdit(request: CommentEditRequest): Promise<CommentRecord> {
    return this.transport.command('comment.edit', request);
  }

  queryCommentRevisions(request: CommentRevisionsQuery): Promise<CommentRevisionsResponse> {
    return this.transport.query('comment.revisions', request);
  }

  commandRulingRecord(request: RulingRecordRequest): Promise<RulingRecord> {
    return this.transport.command('ruling.record', request);
  }

  commandRulingSupersede(request: RulingSupersedeRequest): Promise<RulingRecord> {
    return this.transport.command('ruling.supersede', request);
  }

  queryRulingList(request: RulingListQuery): Promise<RulingListResponse> {
    return this.transport.query('ruling.list', request);
  }

  commandDeferralRecord(request: DeferralRecordRequest): Promise<DeferralRecord> {
    return this.transport.command('deferral.record', request);
  }

  commandDeferralSupersede(request: DeferralSupersedeRequest): Promise<DeferralRecord> {
    return this.transport.command('deferral.supersede', request);
  }

  queryDeferralList(request: DeferralListQuery): Promise<DeferralListResponse> {
    return this.transport.query('deferral.list', request);
  }
}
