// Generated by kanban-contracts-gen. Do not edit.

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonValue }
  | JsonValue[];

export type ApiError = {
  code: ErrorCode;
  current_version?: number | null;
  message: string;
};
export type CloneCreateRequest = {
  branch: string;
  mutation: MutationContext;
  path: string;
  project_id: number;
};
export type CloneCreatedRecord = {
  branch: string;
  path: string;
  project_id: number;
};
export type CloneRemoveRequest = {
  mutation: MutationContext;
  workspace_id: number;
};
export type CloneRemovedRecord = {
  branch?: string | null;
  path: string;
  project_id: number;
  workspace_id: number;
};
export type CommentCreateRequest = {
  mutation: MutationContext;
  project_id: number;
  target: TimelineEntityRef;
  text: string;
};
export type CommentEditRequest = {
  comment_id: number;
  mutation: MutationContext;
  text: string;
};
export type CommentRecord = {
  id: number;
  project_id: number;
  target: TimelineEntityRef;
  text: string;
  version: number;
};
export type CommentRevisionRecord = {
  recorded_at: string;
  revision: number;
  text: string;
};
export type CommentRevisionsQuery = {
  comment_id: number;
};
export type CommentRevisionsResponse = {
  comment: CommentRecord;
  revisions: CommentRevisionRecord[];
};
export type CoverageCriterionProposal = {
  outcome: string;
  stories: string[];
};
export type CriterionRefusal = 'no_outcome' | 'unlinked' | 'technical_command' | 'malformed_story' | 'foreign_story';
export type DeferralIdentity = {
  id: number;
};
export type DeferralListQuery = {
  finding_id?: string | null;
  project_id: number;
};
export type DeferralListResponse = {
  deferrals: DeferralRecord[];
};
export type DeferralRecord = {
  finding_id: string;
  id: number;
  project_id: number;
  reason: string;
  recorded_at: string;
  supersedes_id?: number | null;
};
export type DeferralRecordRequest = {
  finding_id: string;
  mutation: MutationContext;
  project_id: number;
  reason: string;
};
export type DeferralSupersedeRequest = {
  deferral_id: number;
  mutation: MutationContext;
  project_id: number;
  reason: string;
};
export type DiagnosticsExportQuery = Record<string, never>;
export type DiagnosticsExportResponse = {
  bundle_dir: string;
};
export type ErrorCode = 'unknown_field' | 'stale_version' | 'duplicate_idempotency_key' | 'not_found' | 'invalid_request' | 'internal';
export type EventEnvelope = {
  event_type: string;
  payload: JsonValue;
  sequence: number;
};
export type EvidenceAttachRequest = {
  commit_identity?: string | null;
  content_base64?: string | null;
  entity_id: string;
  entity_kind: string;
  evidence_kind: EvidenceKindDto;
  mutation: MutationContext;
  project_id: number;
  relative_path?: string | null;
};
export type EvidenceKindDto = 'managed_file' | 'repository';
export type EvidenceListQuery = {
  entity_id?: string | null;
  entity_kind?: string | null;
  project_id: number;
};
export type EvidenceListResponse = {
  evidence: EvidenceRecord[];
};
export type EvidenceListSummary = {
  count: number;
  project_id: number;
};
export type EvidenceRecord = {
  commit_identity?: string | null;
  content_hash?: string | null;
  entity_id: string;
  entity_kind: string;
  evidence_kind: EvidenceKindDto;
  id: number;
  project_id: number;
  relative_path?: string | null;
};
export type ExportDriftEntry = {
  path: string;
  status: ExportDriftStatus;
};
export type ExportDriftQuery = {
  directory: string;
  project_id: number;
};
export type ExportDriftResponse = {
  directory: string;
  entries: ExportDriftEntry[];
  in_drift: boolean;
  project_id: number;
};
export type ExportDriftStatus = 'missing' | 'differs' | 'unmatched';
export type ExportRenderRequest = {
  directory: string;
  mutation: MutationContext;
  project_id: number;
};
export type ExportRenderResponse = {
  directory: string;
  files: string[];
  project_id: number;
};
export type HealthQuery = Record<string, never>;
export type HealthResponse = {
  connected: boolean;
  service_version: string;
};
export type HerdrConnectionDiagnostics = {
  connected: boolean;
  herdr_workspace: string;
  last_error?: string | null;
  last_snapshot_at?: string | null;
  product_workspace: string;
  session_name?: string | null;
};
export type HerdrDefaultsGetQuery = Record<string, never>;
export type HerdrDefaultsGetResponse = {
  defaults: HerdrGlobalDefaults;
};
export type HerdrDefaultsUpdateRequest = {
  missing_result_deadline_secs: number;
  mutation: MutationContext;
  reconciliation_interval_secs: number;
  stall_deadline_secs: number;
};
export type HerdrGlobalDefaults = {
  missing_result_deadline_secs: number;
  reconciliation_interval_secs: number;
  stall_deadline_secs: number;
  version: number;
};
export type HerdrProjectSettings = {
  missing_result_deadline_secs: number;
  polling_fallback_enabled: boolean;
  polling_fallback_interval_secs: number;
  reconciliation_interval_secs: number;
  stall_deadline_secs: number;
  version: number;
};
export type HerdrSettingsGetQuery = {
  project_id: number;
};
export type HerdrSettingsGetResponse = {
  diagnostics: HerdrConnectionDiagnostics;
  project_id: number;
  settings: HerdrProjectSettings;
};
export type HerdrSettingsUpdateRequest = {
  missing_result_deadline_secs: number;
  mutation: MutationContext;
  polling_fallback_enabled: boolean;
  polling_fallback_interval_secs: number;
  project_id: number;
  reconciliation_interval_secs: number;
  stall_deadline_secs: number;
};
export type InitiativeArchiveRequest = {
  initiative_id: number;
  mutation: MutationContext;
};
export type InitiativeCreateRequest = {
  mutation: MutationContext;
  name: string;
};
export type InitiativeListQuery = Record<string, never>;
export type InitiativeListResponse = {
  initiatives: InitiativeRecord[];
};
export type InitiativeRecord = {
  archived: boolean;
  id: number;
  name: string;
  version: number;
};
export type InitiativeRenameRequest = {
  initiative_id: number;
  mutation: MutationContext;
  name: string;
};
export type LaneCreateRequest = {
  mutation: MutationContext;
  project_id: number;
};
export type LaneListQuery = {
  project_id: number;
};
export type LaneListResponse = {
  lanes: LaneRecord[];
};
export type LaneRecord = {
  id: number;
  project_id: number;
  ticket_id?: number | null;
  version: number;
  workspace_id?: number | null;
};
export type LaneTicketAssignRequest = {
  lane_id: number;
  mutation: MutationContext;
  ticket_id: number;
};
export type LaneTicketReleaseRequest = {
  lane_id: number;
  mutation: MutationContext;
};
export type LaneWorkspaceAssignRequest = {
  lane_id: number;
  mutation: MutationContext;
  workspace_id: number;
};
export type LaneWorkspaceReleaseRequest = {
  lane_id: number;
  mutation: MutationContext;
};
export type LiveEventName = 'initiative.created' | 'initiative.renamed' | 'initiative.archived' | 'project.registered' | 'project.archived' | 'plan.created' | 'plan.activated' | 'plan.replanned' | 'plan.completed' | 'plan.cancelled' | 'plan.archived' | 'spec.created' | 'spec.planned' | 'spec.version.approved' | 'spec.version.superseded' | 'spec.execution.moved' | 'ticket.created' | 'ticket.assigned' | 'profile.defined' | 'profile.updated' | 'profile.retired' | 'comment.created' | 'comment.edited' | 'ruling.recorded' | 'ruling.superseded' | 'deferral.recorded' | 'deferral.superseded' | 'evidence.attached' | 'evidence.listed' | 'workspace.registered' | 'workspace.observed' | 'workspace.retired' | 'lane.created' | 'lane.workspace.assigned' | 'lane.workspace.released' | 'lane.ticket.assigned' | 'lane.ticket.released' | 'clone.created' | 'clone.removed';
export type MutationContext = {
  idempotency_key: string;
  optimistic_version: number;
};
export type PlanActivateRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanArchiveRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanCancelRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanCompleteRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanCoverageGap = {
  claims_no_stories: boolean;
  spec_number: number;
  uncovered: string[];
};
export type PlanCreateRequest = {
  mutation: MutationContext;
  project_id: number;
};
export type PlanCycle = {
  spec_numbers: number[];
};
export type PlanDiagnosticsQuery = {
  plan_id: number;
  version?: number | null;
};
export type PlanDiagnosticsResponse = {
  blocking: boolean;
  coverage_gaps: PlanCoverageGap[];
  cycles: PlanCycle[];
  invalid_profiles: PlanInvalidProfile[];
};
export type PlanEdge = {
  from_spec: number;
  to_spec: number;
};
export type PlanEdgeAddRequest = {
  from_spec: number;
  mutation: MutationContext;
  plan_id: number;
  to_spec: number;
};
export type PlanEdgeRemoveRequest = {
  from_spec: number;
  mutation: MutationContext;
  plan_id: number;
  to_spec: number;
};
export type PlanGetQuery = {
  plan_id: number;
};
export type PlanGetResponse = {
  plan: PlanRecord;
  versions: PlanVersionRecord[];
};
export type PlanInvalidProfile = {
  reference: string;
};
export type PlanListQuery = {
  project_id: number;
};
export type PlanListResponse = {
  plans: PlanRecord[];
};
export type PlanRecord = {
  edges: PlanEdge[];
  id: number;
  number: number;
  project_id: number;
  spec_numbers: number[];
  state: PlanState;
  version: number;
};
export type PlanReplanRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanSpecAddRequest = {
  mutation: MutationContext;
  plan_id: number;
  spec_number: number;
};
export type PlanSpecMoveRequest = {
  mutation: MutationContext;
  plan_id: number;
  position: number;
  spec_number: number;
};
export type PlanSpecRemoveRequest = {
  mutation: MutationContext;
  plan_id: number;
  spec_number: number;
};
export type PlanState = 'draft' | 'active' | 'complete' | 'cancelled' | 'archived';
export type PlanVersionRecord = {
  edges: PlanEdge[];
  number: number;
  spec_numbers: number[];
};
export type ProfileDefineRequest = {
  effort: string;
  fallback?: string | null;
  harness: string;
  model: string;
  mutation: MutationContext;
  name: string;
  usage_pool: string;
};
export type ProfileGetQuery = {
  name: string;
};
export type ProfileListQuery = Record<string, never>;
export type ProfileListResponse = {
  profiles: ProfileRecord[];
};
export type ProfileRecord = {
  effort: string;
  fallback?: string | null;
  harness: string;
  model: string;
  name: string;
  retired: boolean;
  usage_pool: string;
  version: number;
};
export type ProfileRetireRequest = {
  mutation: MutationContext;
  name: string;
};
export type ProfileUpdateRequest = {
  effort: string;
  fallback?: string | null;
  harness: string;
  model: string;
  mutation: MutationContext;
  name: string;
  usage_pool: string;
};
export type ProjectArchiveRequest = {
  mutation: MutationContext;
  project_id: number;
};
export type ProjectCounters = {
  plan: number;
  spec: number;
  ticket: number;
};
export type ProjectListQuery = Record<string, never>;
export type ProjectListResponse = {
  projects: ProjectRecord[];
};
export type ProjectRecord = {
  archived: boolean;
  code: string;
  counters: ProjectCounters;
  default_branch: string;
  herdr_session?: string | null;
  herdr_workspace: string;
  id: number;
  initiative_id?: number | null;
  name: string;
  repository: string;
  seed_workspace: string;
  version: number;
};
export type ProjectRegisterRequest = {
  code: string;
  default_branch: string;
  herdr_session?: string | null;
  herdr_workspace: string;
  initiative_id?: number | null;
  mutation: MutationContext;
  name: string;
  repository: string;
  seed_workspace: string;
};
export type RefusedCriterion = {
  outcome: string;
  reason: CriterionRefusal;
};
export type RulingIdentity = {
  id: number;
};
export type RulingListQuery = {
  entity?: TimelineEntityRef | null;
  project_id: number;
};
export type RulingListResponse = {
  rulings: RulingRecord[];
};
export type RulingRecord = {
  entity?: TimelineEntityRef | null;
  id: number;
  project_id: number;
  recorded_at: string;
  summary: string;
  supersedes_id?: number | null;
};
export type RulingRecordRequest = {
  entity?: TimelineEntityRef | null;
  mutation: MutationContext;
  project_id: number;
  summary: string;
};
export type RulingSupersedeRequest = {
  mutation: MutationContext;
  project_id: number;
  ruling_id: number;
  summary: string;
};
export type SpecContent = {
  further_notes: string;
  implementation_decisions: string;
  name: string;
  out_of_scope: string;
  problem_statement: string;
  short_description: string;
  solution: string;
  testing_decisions: string;
  user_stories: string;
};
export type SpecContentState = 'draft' | 'approved' | 'superseded';
export type SpecContentUpdateRequest = {
  content: SpecContent;
  mutation: MutationContext;
  spec_id: number;
};
export type SpecCoverageCheckQuery = {
  criteria: CoverageCriterionProposal[];
  spec_id: number;
  version: number;
};
export type SpecCoverageCheckResponse = {
  executable: boolean;
  refused: RefusedCriterion[];
  scope: string[];
  uncovered: string[];
};
export type SpecCreateRequest = {
  content: SpecContent;
  mutation: MutationContext;
  project_id: number;
};
export type SpecExecutionMoveRequest = {
  execution: SpecExecutionState;
  mutation: MutationContext;
  spec_id: number;
};
export type SpecExecutionState = 'unplanned' | 'planned' | 'blocked' | 'ready' | 'active' | 'integration_review' | 'complete' | 'cancelled';
export type SpecGetQuery = {
  spec_id: number;
};
export type SpecGetResponse = {
  spec: SpecRecord;
  versions: SpecVersionRecord[];
};
export type SpecListQuery = {
  project_id: number;
};
export type SpecListResponse = {
  specs: SpecRecord[];
};
export type SpecPlanJoinRequest = {
  mutation: MutationContext;
  plan_id: number;
  spec_id: number;
};
export type SpecRecord = {
  execution: SpecExecutionState;
  id: number;
  name: string;
  number: number;
  plan_id?: number | null;
  project_id: number;
  version: number;
};
export type SpecVersionApproveRequest = {
  mutation: MutationContext;
  spec_id: number;
};
export type SpecVersionGetQuery = {
  number: number;
  spec_id: number;
};
export type SpecVersionRecord = {
  content: SpecContent;
  number: number;
  state: SpecContentState;
};
export type SpecVersionSupersedeRequest = {
  mutation: MutationContext;
  spec_id: number;
  version: number;
};
export type TaskMode = 'human' | 'agent';
export type TaskSubtype = 'operational' | 'investigative' | 'administrative' | 'research' | 'prototype' | 'migration' | 'manual';
export type TicketAssignRequest = {
  mutation: MutationContext;
  profile: string;
  ticket_id: number;
};
export type TicketBlockerAddRequest = {
  description: string;
  mutation: MutationContext;
  ticket_id: number;
};
export type TicketBlockerRecord = {
  description: string;
  id: number;
  ticket_id: number;
};
export type TicketBlockerRemoveRequest = {
  blocker_id: number;
  mutation: MutationContext;
  ticket_id: number;
};
export type TicketBugFactsRequest = {
  evidence_ids: number[];
  external_references: TicketExternalReference[];
  mutation: MutationContext;
  occurrence_snapshots: TicketOccurrenceSnapshot[];
  ticket_id: number;
};
export type TicketBugQualification = {
  affected_scope: string;
  criteria: TicketCriterion[];
  environment: string;
  expected_behaviour: string;
  frequency: string;
  reproduction: string;
  risk: string;
  severity: TicketSeverity;
  verification_steps: TicketVerificationStep[];
};
export type TicketBugQualifyRequest = {
  mutation: MutationContext;
  qualification: TicketBugQualification;
  ticket_id: number;
};
export type TicketBugRecord = {
  actual_behaviour: string;
  evidence_ids: number[];
  external_references: TicketExternalReference[];
  occurrence_snapshots: TicketOccurrenceSnapshot[];
  qualification?: TicketBugQualification | null;
  reporter_evidence: string;
};
export type TicketCreateRequest = {
  actual_behaviour?: string | null;
  completion?: string[] | null;
  criteria?: TicketCriterion[] | null;
  due?: string | null;
  kind: TicketKind;
  mode?: TaskMode | null;
  mutation: MutationContext;
  priority: TicketPriority;
  project_id: number;
  reporter_evidence?: string | null;
  scheduled_for?: string | null;
  slice?: string | null;
  spec_id?: number | null;
  subtype?: TaskSubtype | null;
  title?: string | null;
};
export type TicketCriterion = {
  outcome: string;
  stories: string[];
};
export type TicketDependenciesQuery = {
  ticket_id: number;
};
export type TicketDependenciesResponse = {
  blockers: TicketBlockerRecord[];
  dependencies: TicketDependencyRecord[];
  ticket_id: number;
  version: number;
};
export type TicketDependencyAddRequest = {
  from_ticket: number;
  mutation: MutationContext;
  to_ticket: number;
};
export type TicketDependencyRecord = {
  from_number: number;
  from_project_id: number;
  from_state: TicketState;
  from_ticket_id: number;
};
export type TicketDependencyRemoveRequest = {
  from_ticket: number;
  mutation: MutationContext;
  to_ticket: number;
};
export type TicketExternalReference = {
  label?: string | null;
  uri: string;
};
export type TicketGetQuery = {
  ticket_id: number;
};
export type TicketKind = 'implementation' | 'bug' | 'task';
export type TicketListQuery = {
  project_id: number;
};
export type TicketListResponse = {
  tickets: TicketRecord[];
};
export type TicketOccurrenceSnapshot = {
  observation: string;
  observed_at: string;
};
export type TicketPriority = 'urgent' | 'high' | 'normal' | 'low';
export type TicketReadinessBlocker = {
  Ticket: {
    from_number: number;
    from_project_id: number;
    from_state: TicketState;
    from_ticket_id: number;
  };
} | {
  External: {
    blocker_id: number;
    description: string;
  };
};
export type TicketReadinessQuery = {
  ticket_id: number;
};
export type TicketReadinessResponse = {
  blocked_by: TicketReadinessBlocker[];
  ready: boolean;
  state: TicketState;
  ticket_id: number;
};
export type TicketRecord = {
  bug?: TicketBugRecord | null;
  completion: string[];
  criteria: TicketCriterion[];
  due?: string | null;
  id: number;
  kind: TicketKind;
  mode?: TaskMode | null;
  number: number;
  priority: TicketPriority;
  profile?: string | null;
  project_id: number;
  scheduled_for?: string | null;
  slice?: string | null;
  spec_id?: number | null;
  state: TicketState;
  subtype?: TaskSubtype | null;
  title?: string | null;
  version: number;
};
export type TicketSeverity = 'critical' | 'high' | 'medium' | 'low';
export type TicketState = 'draft' | 'parked' | 'blocked' | 'scheduled' | 'ready' | 'active' | 'in_review' | 'approved' | 'landing' | 'done' | 'cancelled' | 'superseded';
export type TicketVerificationStep = {
  command: string;
};
export type TimelineEntityKind = 'initiative' | 'project' | 'plan' | 'spec' | 'ticket' | 'run' | 'review' | 'finding' | 'evidence' | 'comment' | 'workspace' | 'lane' | 'profile';
export type TimelineEntityRef = {
  id: string;
  kind: TimelineEntityKind;
};
export type TimelineEventKind = 'transition' | 'run' | 'telemetry' | 'review' | 'finding' | 'evidence' | 'comment' | 'deferral' | 'ruling';
export type TimelineEventRecord = {
  detail: JsonValue;
  entity?: TimelineEntityRef | null;
  id: number;
  kind: TimelineEventKind;
  recorded_at: string;
  scope: TimelineScope;
};
export type TimelineQuery = {
  entity?: TimelineEntityRef | null;
  kinds?: TimelineEventKind[] | null;
  scope: TimelineScope;
  since?: string | null;
  until?: string | null;
};
export type TimelineQueryResponse = {
  events: TimelineEventRecord[];
};
export type TimelineScope = 'global' | {
  project: number;
};
export type WorkspaceCheckoutDto = 'branch' | 'detached';
export type WorkspaceHealthDto = 'available' | 'assigned' | 'dirty' | 'missing' | 'retired' | 'unobserved';
export type WorkspaceListQuery = {
  project_id: number;
};
export type WorkspaceListResponse = {
  workspaces: WorkspaceRecord[];
};
export type WorkspaceObservationDto = {
  branch?: string | null;
  checkout?: WorkspaceCheckoutDto | null;
  head?: string | null;
  lane_assignment?: number | null;
  repository_identity?: string | null;
  unique_unlanded_commits?: boolean | null;
  working_tree_clean?: boolean | null;
};
export type WorkspaceObserveRequest = {
  mutation: MutationContext;
  workspace_id: number;
};
export type WorkspaceRecord = {
  health: WorkspaceHealthDto;
  id: number;
  is_seed: boolean;
  observation: WorkspaceObservationDto;
  path: string;
  project_id: number;
  reuse: WorkspaceReuseDto;
  version: number;
};
export type WorkspaceRegisterRequest = {
  mutation: MutationContext;
  path: string;
  project_id: number;
};
export type WorkspaceRetireRequest = {
  mutation: MutationContext;
  workspace_id: number;
};
export type WorkspaceReuseDto = {
  clean: boolean;
  free_of_unlanded_commits: boolean;
  reusable: boolean;
  unassigned: boolean;
};
