// Generated by kanban-contracts-gen. Do not edit.

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonValue }
  | JsonValue[];

export type ApiError = {
  code: ErrorCode;
  current_version?: number | null;
  message: string;
};
export type CommentCreateRequest = {
  mutation: MutationContext;
  project_id: string;
  target: TimelineEntityRef;
  text: string;
};
export type CommentEditRequest = {
  comment_id: number;
  mutation: MutationContext;
  text: string;
};
export type CommentRecord = {
  id: number;
  project_id: string;
  target: TimelineEntityRef;
  text: string;
  version: number;
};
export type CommentRevisionRecord = {
  recorded_at: string;
  revision: number;
  text: string;
};
export type CommentRevisionsQuery = {
  comment_id: number;
};
export type CommentRevisionsResponse = {
  comment: CommentRecord;
  revisions: CommentRevisionRecord[];
};
export type DeferralListQuery = {
  finding_id?: string | null;
  project_id: string;
};
export type DeferralListResponse = {
  deferrals: DeferralRecord[];
};
export type DeferralRecord = {
  finding_id: string;
  id: number;
  project_id: string;
  reason: string;
  recorded_at: string;
  supersedes_id?: number | null;
};
export type DeferralRecordRequest = {
  finding_id: string;
  mutation: MutationContext;
  project_id: string;
  reason: string;
};
export type DeferralSupersedeRequest = {
  deferral_id: number;
  mutation: MutationContext;
  project_id: string;
  reason: string;
};
export type ErrorCode = 'unknown_field' | 'stale_version' | 'duplicate_idempotency_key' | 'not_found' | 'invalid_request' | 'internal';
export type EventEnvelope = {
  event_type: string;
  payload: JsonValue;
  sequence: number;
};
export type HealthQuery = Record<string, never>;
export type HealthResponse = {
  connected: boolean;
  service_version: string;
};
export type InitiativeArchiveRequest = {
  initiative_id: number;
  mutation: MutationContext;
};
export type InitiativeCreateRequest = {
  mutation: MutationContext;
  name: string;
};
export type InitiativeListQuery = Record<string, never>;
export type InitiativeListResponse = {
  initiatives: InitiativeRecord[];
};
export type InitiativeRecord = {
  archived: boolean;
  id: number;
  name: string;
  version: number;
};
export type InitiativeRenameRequest = {
  initiative_id: number;
  mutation: MutationContext;
  name: string;
};
export type MutationContext = {
  idempotency_key: string;
  optimistic_version: number;
};
export type RulingListQuery = {
  entity?: TimelineEntityRef | null;
  project_id: string;
};
export type RulingListResponse = {
  rulings: RulingRecord[];
};
export type RulingRecord = {
  entity?: TimelineEntityRef | null;
  id: number;
  project_id: string;
  recorded_at: string;
  summary: string;
  supersedes_id?: number | null;
};
export type RulingRecordRequest = {
  entity?: TimelineEntityRef | null;
  mutation: MutationContext;
  project_id: string;
  summary: string;
};
export type RulingSupersedeRequest = {
  mutation: MutationContext;
  project_id: string;
  ruling_id: number;
  summary: string;
};
export type TimelineEntityKind = 'initiative' | 'project' | 'plan' | 'spec' | 'ticket' | 'run' | 'review' | 'finding' | 'evidence' | 'comment';
export type TimelineEntityRef = {
  id: string;
  kind: TimelineEntityKind;
};
export type TimelineEventKind = 'transition' | 'run' | 'telemetry' | 'review' | 'finding' | 'evidence' | 'comment' | 'deferral' | 'ruling';
export type TimelineEventRecord = {
  detail: JsonValue;
  entity?: TimelineEntityRef | null;
  id: number;
  kind: TimelineEventKind;
  project_id: string;
  recorded_at: string;
};
export type TimelineQuery = {
  entity?: TimelineEntityRef | null;
  kinds?: TimelineEventKind[] | null;
  project_id: string;
  since?: string | null;
  until?: string | null;
};
export type TimelineQueryResponse = {
  events: TimelineEventRecord[];
};
