// Generated by kanban-contracts-gen. Do not edit.

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonValue }
  | JsonValue[];

export type ApiError = {
  code: ErrorCode;
  current_version?: number | null;
  message: string;
};
export type CommentCreateRequest = {
  mutation: MutationContext;
  project_id: number;
  target: TimelineEntityRef;
  text: string;
};
export type CommentEditRequest = {
  comment_id: number;
  mutation: MutationContext;
  text: string;
};
export type CommentRecord = {
  id: number;
  project_id: number;
  target: TimelineEntityRef;
  text: string;
  version: number;
};
export type CommentRevisionRecord = {
  recorded_at: string;
  revision: number;
  text: string;
};
export type CommentRevisionsQuery = {
  comment_id: number;
};
export type CommentRevisionsResponse = {
  comment: CommentRecord;
  revisions: CommentRevisionRecord[];
};
export type CoverageCriterionProposal = {
  outcome: string;
  stories: string[];
};
export type CriterionRefusal = 'no_outcome' | 'unlinked' | 'technical_command' | 'malformed_story' | 'foreign_story';
export type DeferralIdentity = {
  id: number;
};
export type DeferralListQuery = {
  finding_id?: string | null;
  project_id: number;
};
export type DeferralListResponse = {
  deferrals: DeferralRecord[];
};
export type DeferralRecord = {
  finding_id: string;
  id: number;
  project_id: number;
  reason: string;
  recorded_at: string;
  supersedes_id?: number | null;
};
export type DeferralRecordRequest = {
  finding_id: string;
  mutation: MutationContext;
  project_id: number;
  reason: string;
};
export type DeferralSupersedeRequest = {
  deferral_id: number;
  mutation: MutationContext;
  project_id: number;
  reason: string;
};
export type ErrorCode = 'unknown_field' | 'stale_version' | 'duplicate_idempotency_key' | 'not_found' | 'invalid_request' | 'internal';
export type EventEnvelope = {
  event_type: string;
  payload: JsonValue;
  sequence: number;
};
export type EvidenceAttachRequest = {
  commit_identity?: string | null;
  content_base64?: string | null;
  entity_id: string;
  entity_kind: string;
  evidence_kind: EvidenceKindDto;
  mutation: MutationContext;
  project_id: number;
  relative_path?: string | null;
};
export type EvidenceKindDto = 'managed_file' | 'repository';
export type EvidenceListQuery = {
  entity_id?: string | null;
  entity_kind?: string | null;
  project_id: number;
};
export type EvidenceListResponse = {
  evidence: EvidenceRecord[];
};
export type EvidenceListSummary = {
  count: number;
  project_id: number;
};
export type EvidenceRecord = {
  commit_identity?: string | null;
  content_hash?: string | null;
  entity_id: string;
  entity_kind: string;
  evidence_kind: EvidenceKindDto;
  id: number;
  project_id: number;
  relative_path?: string | null;
};
export type HealthQuery = Record<string, never>;
export type HealthResponse = {
  connected: boolean;
  service_version: string;
};
export type HerdrConnectionDiagnostics = {
  connected: boolean;
  herdr_workspace: string;
  last_error?: string | null;
  last_snapshot_at?: string | null;
  product_workspace: string;
  session_name?: string | null;
};
export type HerdrDefaultsGetQuery = Record<string, never>;
export type HerdrDefaultsGetResponse = {
  defaults: HerdrGlobalDefaults;
};
export type HerdrDefaultsUpdateRequest = {
  missing_result_deadline_secs: number;
  mutation: MutationContext;
  reconciliation_interval_secs: number;
  stall_deadline_secs: number;
};
export type HerdrGlobalDefaults = {
  missing_result_deadline_secs: number;
  reconciliation_interval_secs: number;
  stall_deadline_secs: number;
  version: number;
};
export type HerdrProjectSettings = {
  missing_result_deadline_secs: number;
  polling_fallback_enabled: boolean;
  polling_fallback_interval_secs: number;
  reconciliation_interval_secs: number;
  stall_deadline_secs: number;
  version: number;
};
export type HerdrSettingsGetQuery = {
  project_id: number;
};
export type HerdrSettingsGetResponse = {
  diagnostics: HerdrConnectionDiagnostics;
  project_id: number;
  settings: HerdrProjectSettings;
};
export type HerdrSettingsUpdateRequest = {
  missing_result_deadline_secs: number;
  mutation: MutationContext;
  polling_fallback_enabled: boolean;
  polling_fallback_interval_secs: number;
  project_id: number;
  reconciliation_interval_secs: number;
  stall_deadline_secs: number;
};
export type InitiativeArchiveRequest = {
  initiative_id: number;
  mutation: MutationContext;
};
export type InitiativeCreateRequest = {
  mutation: MutationContext;
  name: string;
};
export type InitiativeListQuery = Record<string, never>;
export type InitiativeListResponse = {
  initiatives: InitiativeRecord[];
};
export type InitiativeRecord = {
  archived: boolean;
  id: number;
  name: string;
  version: number;
};
export type InitiativeRenameRequest = {
  initiative_id: number;
  mutation: MutationContext;
  name: string;
};
export type LiveEventName = 'initiative.created' | 'initiative.renamed' | 'initiative.archived' | 'project.registered' | 'project.archived' | 'plan.created' | 'plan.activated' | 'plan.replanned' | 'plan.completed' | 'plan.cancelled' | 'plan.archived' | 'spec.created' | 'spec.planned' | 'spec.version.approved' | 'spec.version.superseded' | 'spec.execution.moved' | 'comment.created' | 'comment.edited' | 'ruling.recorded' | 'ruling.superseded' | 'deferral.recorded' | 'deferral.superseded' | 'evidence.attached' | 'evidence.listed' | 'workspace.registered' | 'workspace.observed' | 'workspace.retired';
export type MutationContext = {
  idempotency_key: string;
  optimistic_version: number;
};
export type PlanActivateRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanArchiveRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanCancelRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanCompleteRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanCreateRequest = {
  mutation: MutationContext;
  project_id: number;
};
export type PlanEdge = {
  from_spec: number;
  to_spec: number;
};
export type PlanEdgeAddRequest = {
  from_spec: number;
  mutation: MutationContext;
  plan_id: number;
  to_spec: number;
};
export type PlanEdgeRemoveRequest = {
  from_spec: number;
  mutation: MutationContext;
  plan_id: number;
  to_spec: number;
};
export type PlanGetQuery = {
  plan_id: number;
};
export type PlanGetResponse = {
  plan: PlanRecord;
  versions: PlanVersionRecord[];
};
export type PlanListQuery = {
  project_id: number;
};
export type PlanListResponse = {
  plans: PlanRecord[];
};
export type PlanRecord = {
  edges: PlanEdge[];
  id: number;
  number: number;
  project_id: number;
  spec_numbers: number[];
  state: PlanState;
  version: number;
};
export type PlanReplanRequest = {
  mutation: MutationContext;
  plan_id: number;
};
export type PlanSpecAddRequest = {
  mutation: MutationContext;
  plan_id: number;
  spec_number: number;
};
export type PlanSpecMoveRequest = {
  mutation: MutationContext;
  plan_id: number;
  position: number;
  spec_number: number;
};
export type PlanSpecRemoveRequest = {
  mutation: MutationContext;
  plan_id: number;
  spec_number: number;
};
export type PlanState = 'draft' | 'active' | 'complete' | 'cancelled' | 'archived';
export type PlanVersionRecord = {
  edges: PlanEdge[];
  number: number;
  spec_numbers: number[];
};
export type ProjectArchiveRequest = {
  mutation: MutationContext;
  project_id: number;
};
export type ProjectCounters = {
  plan: number;
  spec: number;
  ticket: number;
};
export type ProjectListQuery = Record<string, never>;
export type ProjectListResponse = {
  projects: ProjectRecord[];
};
export type ProjectRecord = {
  archived: boolean;
  code: string;
  counters: ProjectCounters;
  default_branch: string;
  herdr_session?: string | null;
  herdr_workspace: string;
  id: number;
  initiative_id?: number | null;
  name: string;
  repository: string;
  seed_workspace: string;
  version: number;
};
export type ProjectRegisterRequest = {
  code: string;
  default_branch: string;
  herdr_session?: string | null;
  herdr_workspace: string;
  initiative_id?: number | null;
  mutation: MutationContext;
  name: string;
  repository: string;
  seed_workspace: string;
};
export type RefusedCriterion = {
  outcome: string;
  reason: CriterionRefusal;
};
export type RulingIdentity = {
  id: number;
};
export type RulingListQuery = {
  entity?: TimelineEntityRef | null;
  project_id: number;
};
export type RulingListResponse = {
  rulings: RulingRecord[];
};
export type RulingRecord = {
  entity?: TimelineEntityRef | null;
  id: number;
  project_id: number;
  recorded_at: string;
  summary: string;
  supersedes_id?: number | null;
};
export type RulingRecordRequest = {
  entity?: TimelineEntityRef | null;
  mutation: MutationContext;
  project_id: number;
  summary: string;
};
export type RulingSupersedeRequest = {
  mutation: MutationContext;
  project_id: number;
  ruling_id: number;
  summary: string;
};
export type SpecContent = {
  further_notes: string;
  implementation_decisions: string;
  name: string;
  out_of_scope: string;
  problem_statement: string;
  short_description: string;
  solution: string;
  testing_decisions: string;
  user_stories: string;
};
export type SpecContentState = 'draft' | 'approved' | 'superseded';
export type SpecContentUpdateRequest = {
  content: SpecContent;
  mutation: MutationContext;
  spec_id: number;
};
export type SpecCoverageCheckQuery = {
  criteria: CoverageCriterionProposal[];
  spec_id: number;
  version: number;
};
export type SpecCoverageCheckResponse = {
  executable: boolean;
  refused: RefusedCriterion[];
  scope: string[];
  uncovered: string[];
};
export type SpecCreateRequest = {
  content: SpecContent;
  mutation: MutationContext;
  project_id: number;
};
export type SpecExecutionMoveRequest = {
  execution: SpecExecutionState;
  mutation: MutationContext;
  spec_id: number;
};
export type SpecExecutionState = 'unplanned' | 'planned' | 'blocked' | 'ready' | 'active' | 'integration_review' | 'complete' | 'cancelled';
export type SpecGetQuery = {
  spec_id: number;
};
export type SpecGetResponse = {
  spec: SpecRecord;
  versions: SpecVersionRecord[];
};
export type SpecListQuery = {
  project_id: number;
};
export type SpecListResponse = {
  specs: SpecRecord[];
};
export type SpecPlanJoinRequest = {
  mutation: MutationContext;
  plan_id: number;
  spec_id: number;
};
export type SpecRecord = {
  execution: SpecExecutionState;
  id: number;
  name: string;
  number: number;
  plan_id?: number | null;
  project_id: number;
  version: number;
};
export type SpecVersionApproveRequest = {
  mutation: MutationContext;
  spec_id: number;
};
export type SpecVersionGetQuery = {
  number: number;
  spec_id: number;
};
export type SpecVersionRecord = {
  content: SpecContent;
  number: number;
  state: SpecContentState;
};
export type SpecVersionSupersedeRequest = {
  mutation: MutationContext;
  spec_id: number;
  version: number;
};
export type TimelineEntityKind = 'initiative' | 'project' | 'plan' | 'spec' | 'ticket' | 'run' | 'review' | 'finding' | 'evidence' | 'comment' | 'workspace';
export type TimelineEntityRef = {
  id: string;
  kind: TimelineEntityKind;
};
export type TimelineEventKind = 'transition' | 'run' | 'telemetry' | 'review' | 'finding' | 'evidence' | 'comment' | 'deferral' | 'ruling';
export type TimelineEventRecord = {
  detail: JsonValue;
  entity?: TimelineEntityRef | null;
  id: number;
  kind: TimelineEventKind;
  recorded_at: string;
  scope: TimelineScope;
};
export type TimelineQuery = {
  entity?: TimelineEntityRef | null;
  kinds?: TimelineEventKind[] | null;
  scope: TimelineScope;
  since?: string | null;
  until?: string | null;
};
export type TimelineQueryResponse = {
  events: TimelineEventRecord[];
};
export type TimelineScope = 'global' | {
  project: number;
};
export type WorkspaceCheckoutDto = 'branch' | 'detached';
export type WorkspaceHealthDto = 'available' | 'assigned' | 'dirty' | 'missing' | 'retired';
export type WorkspaceListQuery = {
  project_id: number;
};
export type WorkspaceListResponse = {
  workspaces: WorkspaceRecord[];
};
export type WorkspaceObservationDto = {
  branch?: string | null;
  checkout?: WorkspaceCheckoutDto | null;
  head?: string | null;
  lane_assignment?: number | null;
  repository_identity?: string | null;
  unique_unlanded_commits?: boolean | null;
  working_tree_clean?: boolean | null;
};
export type WorkspaceObserveRequest = {
  mutation: MutationContext;
  workspace_id: number;
};
export type WorkspaceRecord = {
  health: WorkspaceHealthDto;
  id: number;
  is_seed: boolean;
  observation: WorkspaceObservationDto;
  path: string;
  project_id: number;
  reuse: WorkspaceReuseDto;
  version: number;
};
export type WorkspaceRegisterRequest = {
  mutation: MutationContext;
  path: string;
  project_id: number;
};
export type WorkspaceRetireRequest = {
  mutation: MutationContext;
  workspace_id: number;
};
export type WorkspaceReuseDto = {
  clean: boolean;
  free_of_unlanded_commits: boolean;
  reusable: boolean;
  unassigned: boolean;
};
