// Generated by kanban-contracts-gen. Do not edit.
import type { ChipVocabulary } from './types.js';

export const CHIP_VOCABULARY: ChipVocabulary = {
  "version": 1,
  "sets": [
    {
      "kind": "implementation",
      "chips": [
        "priority",
        "progress",
        "spec",
        "implementer",
        "reviewers",
        "lane",
        "blockers"
      ]
    },
    {
      "kind": "bug",
      "chips": [
        "priority",
        "progress",
        "spec",
        "severity",
        "frequency",
        "origin",
        "profiles",
        "blockers"
      ]
    },
    {
      "kind": "task",
      "chips": [
        "priority",
        "progress",
        "subtype",
        "mode",
        "schedule",
        "executor",
        "blockers"
      ]
    }
  ]
};
