use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::catalog::{OperationKind, exposed_operations};
use kanban_dto::schema_definitions;
use schemars::schema::{InstanceType, Schema, SchemaObject, SingleOrVec};

pub fn generate(output_root: &Path) -> io::Result<()> {
    let src_root = output_root.join("src");
    let schemas_dir = src_root.join("schemas");
    fs::create_dir_all(&schemas_dir)?;

    let mut schema_index = BTreeMap::new();
    for (name, schema) in schema_definitions() {
        let schema_value = serde_json::to_value(&schema).map_err(io::Error::other)?;
        let schema_path = schemas_dir.join(format!("{name}.json"));
        fs::write(
            &schema_path,
            format!(
                "{}\n",
                serde_json::to_string_pretty(&schema_value).map_err(io::Error::other)?
            ),
        )?;
        schema_index.insert(name, schema);
    }
    prune_orphaned_schemas(&schemas_dir, &schema_index)?;

    fs::write(src_root.join("types.ts"), render_types(&schema_index)?)?;
    fs::write(src_root.join("client.ts"), render_client(&schema_index)?)?;
    fs::write(
        src_root.join("mcp-tools.json"),
        render_mcp_tools(&schema_index)?,
    )?;
    fs::write(src_root.join("index.ts"), render_index()?)?;

    Ok(())
}

fn prune_orphaned_schemas(
    schemas_dir: &Path,
    schema_index: &BTreeMap<&'static str, schemars::schema::RootSchema>,
) -> io::Result<()> {
    let active_names = schema_index
        .keys()
        .map(|name| format!("{name}.json"))
        .collect::<std::collections::BTreeSet<_>>();

    for entry in fs::read_dir(schemas_dir)? {
        let entry = entry?;
        let file_name = entry.file_name();
        let Some(file_name) = file_name.to_str() else {
            continue;
        };

        if file_name.ends_with(".json") && !active_names.contains(file_name) {
            fs::remove_file(entry.path())?;
        }
    }

    Ok(())
}

fn render_index() -> io::Result<String> {
    Ok("// Generated by kanban-contracts-gen. Do not edit.\n\
         export * from './types.js';\n\
         export * from './client.js';\n"
        .to_owned())
}

fn render_types(
    schema_index: &BTreeMap<&'static str, schemars::schema::RootSchema>,
) -> io::Result<String> {
    let mut output = String::from("// Generated by kanban-contracts-gen. Do not edit.\n\n");
    output.push_str("export type JsonValue =\n");
    output.push_str("  | string\n");
    output.push_str("  | number\n");
    output.push_str("  | boolean\n");
    output.push_str("  | null\n");
    output.push_str("  | { [key: string]: JsonValue }\n");
    output.push_str("  | JsonValue[];\n\n");

    for name in schema_index.keys() {
        let schema = &schema_index[name];
        output.push_str(&render_type_definition(name, schema));
    }

    Ok(output)
}

fn render_type_definition(name: &str, schema: &schemars::schema::RootSchema) -> String {
    let rendered = render_schema_object_type(&schema.schema, schema, 0);
    format!("export type {name} = {rendered};\n")
}

fn render_schema_type(
    schema: &Schema,
    root: &schemars::schema::RootSchema,
    depth: usize,
) -> String {
    match schema {
        Schema::Bool(true) => "JsonValue".to_owned(),
        Schema::Bool(false) => "never".to_owned(),
        Schema::Object(object) => render_schema_object_type(object, root, depth),
    }
}

fn render_schema_object_type(
    object: &SchemaObject,
    root: &schemars::schema::RootSchema,
    depth: usize,
) -> String {
    if let Some(reference) = &object.reference {
        return reference_to_type_name(reference);
    }

    if let Some(enum_values) = &object.enum_values {
        return render_string_enum(enum_values);
    }

    if let Some(subschemas) = &object.subschemas {
        if let Some(any_of) = &subschemas.any_of {
            let variants = any_of
                .iter()
                .map(|schema| render_schema_type(schema, root, depth))
                .collect::<Vec<_>>();
            if !variants.is_empty() {
                return variants.join(" | ");
            }
        }
        if let Some(one_of) = &subschemas.one_of {
            let variants = one_of
                .iter()
                .map(|schema| render_schema_type(schema, root, depth))
                .collect::<Vec<_>>();
            return variants.join(" | ");
        }
    }

    if let Some(instance_type) = &object.instance_type {
        return render_instance_type(instance_type, object, root, depth);
    }

    if object
        .object
        .as_ref()
        .map(|validation| validation.properties.is_empty())
        .unwrap_or(true)
    {
        return "Record<string, never>".to_owned();
    }

    render_interface(object, root, depth)
}

fn render_instance_type(
    instance_type: &SingleOrVec<InstanceType>,
    object: &SchemaObject,
    root: &schemars::schema::RootSchema,
    depth: usize,
) -> String {
    match instance_type {
        SingleOrVec::Single(instance) => match instance.as_ref() {
            InstanceType::Null => "null".to_owned(),
            InstanceType::Boolean => "boolean".to_owned(),
            InstanceType::Integer | InstanceType::Number => "number".to_owned(),
            InstanceType::String => "string".to_owned(),
            InstanceType::Array => {
                let item_type = object
                    .array
                    .as_ref()
                    .and_then(|array| array.items.as_ref())
                    .map(|items| match items {
                        SingleOrVec::Single(schema) => render_schema_type(schema, root, depth + 1),
                        SingleOrVec::Vec(schemas) => schemas
                            .iter()
                            .map(|schema| render_schema_type(schema, root, depth + 1))
                            .collect::<Vec<_>>()
                            .join(" | "),
                    })
                    .unwrap_or_else(|| "unknown".to_owned());
                format!("{item_type}[]")
            }
            InstanceType::Object => render_interface(object, root, depth),
        },
        SingleOrVec::Vec(types) => types
            .iter()
            .map(|instance| {
                render_instance_type(
                    &SingleOrVec::Single(Box::new(*instance)),
                    object,
                    root,
                    depth,
                )
            })
            .collect::<Vec<_>>()
            .join(" | "),
    }
}

fn render_interface(
    object: &SchemaObject,
    root: &schemars::schema::RootSchema,
    depth: usize,
) -> String {
    let object_validation = object.object.as_ref();
    let properties: Vec<_> = object_validation
        .map(|validation| validation.properties.iter().collect())
        .unwrap_or_default();

    if properties.is_empty() {
        return "Record<string, never>".to_owned();
    }

    let indent = "  ".repeat(depth + 1);
    let mut lines = vec!["{".to_owned()];

    for (property_name, property_schema) in properties {
        let property_type = render_schema_type(property_schema, root, depth + 1);
        let optional = object_validation
            .map(|validation| !validation.required.contains(property_name.as_str()))
            .unwrap_or(true);
        let optional_marker = if optional { "?" } else { "" };
        lines.push(format!(
            "{indent}{property_name}{optional_marker}: {property_type};"
        ));
    }

    lines.push(format!("{}}}", "  ".repeat(depth)));
    lines.join("\n")
}

fn render_string_enum(enum_values: &[serde_json::Value]) -> String {
    enum_values
        .iter()
        .map(|value| {
            value
                .as_str()
                .map(|variant| format!("'{variant}'"))
                .unwrap_or_else(|| "never".to_owned())
        })
        .collect::<Vec<_>>()
        .join(" | ")
}

fn reference_to_type_name(reference: &str) -> String {
    reference.rsplit('/').next().unwrap_or(reference).to_owned()
}

fn render_client(
    schema_index: &BTreeMap<&'static str, schemars::schema::RootSchema>,
) -> io::Result<String> {
    let mut referenced_types = BTreeMap::new();
    referenced_types.insert("EventEnvelope", ());

    for operation in exposed_operations() {
        referenced_types.insert(operation.request_schema, ());
        referenced_types.insert(operation.response_schema, ());
    }

    let mut output = String::from("// Generated by kanban-contracts-gen. Do not edit.\n");
    output.push_str("import type { ");
    output.push_str(
        &referenced_types
            .keys()
            .copied()
            .collect::<Vec<_>>()
            .join(", "),
    );
    output.push_str(" } from './types.js';\n\n");

    let mut operation_names = Vec::new();
    for operation in exposed_operations() {
        operation_names.push(format!("  '{}',", operation.name));
    }

    output.push_str("export const KANBAN_CLIENT_OPERATIONS = [\n");
    output.push_str(&operation_names.join("\n"));
    output.push_str("\n] as const;\n\n");
    output.push_str(
        "export type KanbanOperationName = (typeof KANBAN_CLIENT_OPERATIONS)[number];\n\n",
    );
    output.push_str("export interface KanbanTransport {\n");
    output.push_str(
        "  query<Request, Response>(name: KanbanOperationName, request: Request): Promise<Response>;\n",
    );
    output.push_str(
        "  command<Request, Response>(name: KanbanOperationName, request: Request): Promise<Response>;\n",
    );
    output.push_str("  subscribe(handler: (event: EventEnvelope) => void): () => void;\n");
    output.push_str("}\n\n");
    output.push_str("export class KanbanClient {\n");
    output.push_str("  constructor(private readonly transport: KanbanTransport) {}\n\n");

    let operations = exposed_operations();
    for (index, operation) in operations.iter().enumerate() {
        let method_name = operation_method_name(operation.name, operation.kind);
        let request_type = operation.request_schema;
        let response_type = operation.response_schema;
        let transport_method = match operation.kind {
            OperationKind::Query => "query",
            OperationKind::Command => "command",
        };
        let request_parameter = if request_schema_is_empty(schema_index, request_type) {
            format!("request: {request_type} = {{}}")
        } else {
            format!("request: {request_type}")
        };

        output.push_str(&format!(
            "  {method_name}({request_parameter}): Promise<{response_type}> {{\n    return this.transport.{transport_method}('{operation_name}', request);\n  }}",
            method_name = method_name,
            request_parameter = request_parameter,
            response_type = response_type,
            transport_method = transport_method,
            operation_name = operation.name,
        ));
        if index + 1 < operations.len() {
            output.push_str("\n\n");
        } else {
            output.push('\n');
        }
    }

    output.push_str("}\n");
    Ok(output)
}

pub fn operation_method_name(operation_name: &str, kind: OperationKind) -> String {
    let prefix = match kind {
        OperationKind::Query => "query",
        OperationKind::Command => "command",
    };
    let suffix = operation_name
        .split('.')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => {
                    let mut capitalised = first.to_ascii_uppercase().to_string();
                    capitalised.push_str(chars.as_str());
                    capitalised
                }
                None => String::new(),
            }
        })
        .collect::<String>();

    format!("{prefix}{suffix}")
}

fn request_schema_is_empty(
    schema_index: &BTreeMap<&'static str, schemars::schema::RootSchema>,
    schema_name: &str,
) -> bool {
    schema_index
        .get(schema_name)
        .and_then(|schema| schema.schema.object.as_ref())
        .map(|validation| validation.properties.is_empty())
        .unwrap_or(false)
}

fn render_mcp_tools(
    schema_index: &BTreeMap<&'static str, schemars::schema::RootSchema>,
) -> io::Result<String> {
    let tools = exposed_operations()
        .iter()
        .map(|operation| {
            let input_schema = schema_index
                .get(operation.request_schema)
                .map(|schema| serde_json::to_value(schema).expect("schema serialises"))
                .expect("request schema exists");
            let output_schema = schema_index
                .get(operation.response_schema)
                .map(|schema| serde_json::to_value(schema).expect("schema serialises"))
                .expect("response schema exists");

            serde_json::json!({
                "name": operation.mcp_tool_name,
                "description": operation.description,
                "inputSchema": input_schema,
                "outputSchema": output_schema,
            })
        })
        .collect::<Vec<_>>();

    Ok(format!(
        "{}\n",
        serde_json::to_string_pretty(&tools).map_err(io::Error::other)?
    ))
}

pub fn default_output_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../packages/contracts")
}

#[cfg(test)]
mod tests {
    use super::{generate, operation_method_name};
    use crate::catalog::{OperationKind, exposed_operations};
    use std::fs;

    #[test]
    fn generation_is_deterministic() {
        let temp_one =
            std::env::temp_dir().join(format!("kanban-contracts-gen-a-{}", std::process::id()));
        let temp_two =
            std::env::temp_dir().join(format!("kanban-contracts-gen-b-{}", std::process::id()));
        let _ = fs::remove_dir_all(&temp_one);
        let _ = fs::remove_dir_all(&temp_two);

        generate(&temp_one).expect("first generation succeeds");
        generate(&temp_two).expect("second generation succeeds");

        for file_name in ["src/client.ts", "src/types.ts", "src/mcp-tools.json"] {
            let first = fs::read_to_string(temp_one.join(file_name)).expect("first artifact");
            let second = fs::read_to_string(temp_two.join(file_name)).expect("second artifact");
            assert_eq!(first, second, "{file_name} must be deterministic");
        }

        let _ = fs::remove_dir_all(temp_one);
        let _ = fs::remove_dir_all(temp_two);
    }

    #[test]
    fn generated_client_lists_only_exposed_operations() {
        let temp_root =
            std::env::temp_dir().join(format!("kanban-contracts-gen-{}", std::process::id()));
        let _ = fs::remove_dir_all(&temp_root);
        generate(&temp_root).expect("generation succeeds");

        let client_source =
            fs::read_to_string(temp_root.join("src/client.ts")).expect("client exists");
        for operation in exposed_operations() {
            assert!(
                client_source.contains(&format!("'{}'", operation.name)),
                "missing operation `{}` in generated client",
                operation.name
            );
        }

        let operation_count = client_source.matches("this.transport.").count();
        assert_eq!(
            operation_count,
            exposed_operations().len(),
            "generated client must not expose extra operations"
        );

        let _ = fs::remove_dir_all(temp_root);
    }

    #[test]
    fn generation_removes_orphaned_schema_files() {
        let temp_root = std::env::temp_dir().join(format!(
            "kanban-contracts-gen-orphans-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&temp_root);
        generate(&temp_root).expect("initial generation succeeds");

        let orphan_path = temp_root.join("src/schemas/OrphanedSchema.json");
        fs::write(&orphan_path, "{}\n").expect("orphan schema is written");
        assert!(
            orphan_path.is_file(),
            "orphan schema must exist before regeneration"
        );

        generate(&temp_root).expect("regeneration succeeds");
        assert!(
            !orphan_path.exists(),
            "orphaned schema files must be removed during regeneration"
        );

        let _ = fs::remove_dir_all(temp_root);
    }

    #[test]
    fn generated_typescript_has_no_trailing_blank_lines() {
        let temp_root =
            std::env::temp_dir().join(format!("kanban-contracts-gen-eof-{}", std::process::id()));
        let _ = fs::remove_dir_all(&temp_root);
        generate(&temp_root).expect("generation succeeds");

        for file_name in ["src/types.ts", "src/client.ts"] {
            let source =
                fs::read_to_string(temp_root.join(file_name)).expect("generated file exists");
            assert!(
                source.ends_with('\n'),
                "{file_name} must end with a single newline"
            );
            assert!(
                !source.ends_with("\n\n"),
                "{file_name} must not end with a blank line"
            );
        }

        let _ = fs::remove_dir_all(temp_root);
    }

    #[test]
    fn operation_method_names_are_stable() {
        assert_eq!(
            operation_method_name("health.get", OperationKind::Query),
            "queryHealthGet"
        );
    }

    #[test]
    fn optional_schema_properties_render_as_optional_typescript() {
        let temp_root = std::env::temp_dir().join(format!(
            "kanban-contracts-gen-optional-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&temp_root);
        generate(&temp_root).expect("generation succeeds");

        let types = fs::read_to_string(temp_root.join("src/types.ts")).expect("types exist");
        assert!(
            types.contains("current_version?: number | null;"),
            "fields the Rust side may omit must render optional:\n{types}"
        );

        let _ = fs::remove_dir_all(&temp_root);
    }
}
